<a href="https://colab.research.google.com/github/GthingkingG/Machine-Learning/blob/main/Python/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Jupyter Notebook
-> 코드를 블록단위로 나눠서 순차적으로 실행가능
: 하나의 답이 결과물이 아닌, 그 과정 자체가 결과물이된다. 따라서, 다양한 인사이트가 필요한 데이터 사이언스에 적합한 도구이다.

---



+)구글의 colab과의 차이는 colab은 클라우드에 코드를 오려서 사용(환경을 따로 로컬에서 설정할 필요 없다.)하는 반면, Jupyter Notebook은 내 pc에 코드를 넣고 사용(로컬 환경을 설정해야한다.)하는 것이어서 인터넷이 필요없다.

# 커널
: 하나의 세션
-> 같은 커널에 있는 동안에는 셀들이 공간을 공유하고 있어서 함수나 변수를 공유할 수 있다.

# 마크다운 사용하기
: 셀의 타입을 '마크다운'으로 바꿔서 텍스트를 입력할 수 있다.
  -> 마크다운 문법을 사용하면 글의 가독성을 높힐 수 있다.
  
  ex)
  - '# 내용' : 글자 크기 키우기
  - '** 내용 **' : 글자 **볼드체**
  - '* 내용 *' : 글자 *기울이기*
  - '- 내용' : 대시리스트
  - '1. 내용 ': 숫자리스트

In [ ]:
x = 15
print(x)

15


# Numpy[Numerical Python]
: 수치적인 연산에 최적화된 도구

## Numpy Array
-> 단체 연산에 특화되어, 많은 양의 데이터를 다룰 때 좋다.
+)메모리 최적화, 연산 최적화

In [ ]:
import numpy as np


print(np.zeros(8))
print(np.arange(4))
print(np.arange(2, 9))
print(np.arange(1, 10, 4))

array1 = np.array([1, 3, 5, 2])
type(array1)

array2 = np.array([[1, 1, 3], [2, 3, 5], [4, 2, 0]])
print(array1)
print(array2)

print(array1.size)
print(array2.size)

print(array1.shape)
print(array2.shape)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0 1 2 3]
[2 3 4 5 6 7 8]
[1 5 9]
[1 3 5 2]
[[1 1 3]
 [2 3 5]
 [4 2 0]]
4
9
(4,)
(3, 3)


+)ndarray : nd(n차원) 배열

## 인덱싱과 슬라이싱
-> 파이썬의 리스트와 비슷하게 활용가능하다.


In [ ]:
import numpy as np


gdp_array = np.array([1234, 1351, 2194, 4032, 12301, 4204, 50211])

print(gdp_array[0])
print(gdp_array[-2])
print(gdp_array[1: 3])

array1 = np.array([1, 4, 2, 4])
print(gdp_array[array1])

1234
4204
[1351 2194]
[ 1351 12301  2194 12301]


+)numpy array에 리스트를 인덱싱하면 리스트에 있는 원소에 인덱싱된 numpy array가 반환된다.

### 실습)비트코인 가격 정보 탐색하기1

`bitcoin_array`에는 비트코인 투자 열풍이 불었던 2017년의 월별 비트코인 가격이 들어있습니다. 여기서 3분기(7월~9월)의 비트코인 가격만 가져와 보세요.

In [ ]:
import numpy as np

bitcoin_array = np.array([970, 1180, 1072, 1348, 2286, 2481,
                          2875, 4703, 4339, 6468, 10234, 14156])

print(bitcoin_array[6: 9])

[2875 4703 4339]


# 2차원 배열 인덱싱과 슬라이싱
+)row -> 가로줄 / col -> 세로줄

In [ ]:
import numpy as np

gdp_array = np.array([
    [12257, 11561, 13165, 14673, 16496, 19403],  # 대한민국
    [39169, 34406, 32821, 35387, 38299, 37813],  # 일본
    [959, 1053, 1149, 1289, 1509, 1753],         # 중국
    [36335, 37133, 38023, 39496, 41713, 44115]   # 미국
])

print(gdp_array[1]) #일본 gdp
print(gdp_array[1, 3], gdp_array[1][3])
print(gdp_array[1:3, 2:5]) #일본, 중국의 2~4번째 gdp
print(gdp_array[:, 2:4]) #모든 나라의 2~3번째 gdp
print(gdp_array[1:3, :]) #일본, 중국의 모든 gdp

[39169 34406 32821 35387 38299 37813]
35387 35387
[[32821 35387 38299]
 [ 1149  1289  1509]]
[[13165 14673]
 [32821 35387]
 [ 1149  1289]
 [38023 39496]]
[[39169 34406 32821 35387 38299 37813]
 [  959  1053  1149  1289  1509  1753]]


### 실습)비트코인 가격 정보 탐색하기2

이번에 실습에서 살펴볼 bitcoin_array는 2017년 월별 비트코인 가격과 거래량 정보가 들어 있는 2차원 array입니다. 첫 번째 로우에는 가격 정보, 두 번째 로우에는 거래량(천만 기준) 정보가 들어 있죠. 여기서 7월의 비트코인 거래량 정보만 가져와 보세요!

In [ ]:
import numpy as np

bitcoin_array = np.array([[970, 1180, 1072, 1348, 2286, 2481,
						   2875, 4703, 4339, 6468, 10234, 14156],
						  [514, 428, 1087, 976, 3426, 4448,
						   3262, 6355, 5570, 5801, 14074, 41034]])

# 여기에 코드를 작성하세요.
print(bitcoin_array[1][6])

3262


# 불린 인덱싱
-> Numpy Array에서 값에 접근할 때, 위치 기반이 아닌 특정 조건에 따라 인덱싱

In [ ]:
import numpy as np


gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])

print(gdp_array > 10000) #조건식에 따라서, 출력
print(gdp_array[gdp_array>10000]) #조건이 참인 원소만 저장
print(gdp_array) #계산과 저장은 다르다. 따로 Numpy Array에 저장하지 않으면, 원본은 변하지 않는다.

mask = gdp_array > 10000
print(mask)
print(type(mask))
print(gdp_array[mask])

print(gdp_array[(gdp_array < 8000) | (gdp_array > 10000)])
print(gdp_array[(gdp_array > 8000) & (gdp_array < 8500)])

[False False False False  True  True  True  True False  True]
[10385 12565 13403 12398 10672]
[ 6610  7637  8127  8885 10385 12565 13403 12398  8282 10672]
[False False False False  True  True  True  True False  True]
<class 'numpy.ndarray'>
[10385 12565 13403 12398 10672]
[ 6610  7637 10385 12565 13403 12398 10672]
[8127 8282]


+)Numpy Array에 조건식을 추가하면 그 조건에 해당하는 값이 출력되고, Numpy Array에 조건을 인덱싱하면 참인 원소만 Numpy Array에 저장된다.

# Numpy 기본연산
-> Numpy Array의 연산을 효율적으로 해주는 함수들이 존재한다.

In [ ]:
import numpy as np


gdp_korea_array = np.array([12257, 11561, 13165, 14673, 16496, 19403])
gdp_us_array = np.array([36335, 37133, 38023, 39496, 41713, 44115])

print(gdp_korea_array / 100)

print(gdp_korea_array.mean())  #평균값
print(gdp_korea_array.sum())
print(gdp_korea_array.min())
print(gdp_korea_array.max())

print(gdp_korea_array + gdp_us_array)

[122.57 115.61 131.65 146.73 164.96 194.03]
14592.5
87555
11561
19403
[48592 48694 51188 54169 58209 63518]


+)마찬가지로 Numpy Array에 직접 저장하지 않고 계산만하면, 원본은 변하지 않는다.

### 실습)짝수만 추출하기
1부터 100까지 숫자가 들어 있는 numbers_array에서 짝수에 해당하는 숫자들만 뽑아 보세요!

In [ ]:
import numpy as np


numbers_array = np.arange(1, 101)


numbers_array[1::2]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### 실습)쇼핑몰 매출액 계산하기
소원이는 부업으로 인터넷 쇼핑몰 운영을 시작했습니다. 가격은 price_array, 판매 수량은 quantity_array에 저장되어 있는데요. 치마, 티셔츠, 원피스, 스웨터, 코트, 청바지, 신발 순서대로 정보가 들어 있다고 합니다. 각 상품별 매출액을 한번 계산해 볼까요? 실습 코드를 실행하면 아래와 같은 형태의 결과물이 출력되어야 합니다.

In [ ]:
import numpy as np

price_array = np.array([30000, 25000, 40000, 60000, 95000, 35000, 50000])
quantity_array = np.array([10, 13, 7, 20, 6, 19, 9])

# 여기에 코드를 작성하세요.
price_array * quantity_array

array([ 300000,  325000,  280000, 1200000,  570000,  665000,  450000])